#136 implement video source to loop video file
insight-platform/Savant pull request #143
Opened 2023-04-07 10:29 UTC by tomskikh

2023-04-07 10:31 UTC, bwsw commented on adapters/gst/gst_plugins/python/media_files_src_bin.py
> +                ), f'Only "fil-type={FileType.VIDEO.value}" is allowed when "loop-file" is enabled'
Typo in 'fil-type'

2023-04-07 12:41 UTC, bwsw commented on adapters/gst/gst_plugins/python/media_files_src_bin.py
> +                ), f'Only "fil-type={FileType.VIDEO.value}" is allowed when "loop-file" is enabled'
@tomskikh don't forget to update the docs: 
Adapters: https://github.com/insight-platform/Savant/blob/develop/docs/adapters.md
Readme: https://github.com/insight-platform/Savant/
Architecture: https://github.com/insight-platform/Savant/blob/develop/docs/architecture.md

2023-04-11 05:00 UTC, bwsw requested changes

2023-04-11 05:00 UTC, bwsw commented on docs/adapters.md
> +  - [The Looped Video File Source Adapter](#the-looped-video-file-source-adapter)
Please change to Loop Video File Source Adapter, don't use the 'looped' eveywhere.

2023-04-11 05:00 UTC, bwsw commented on docs/adapters.md
> +  - [The Looped Video File Source Adapter](#the-looped-video-file-source-adapter)
We could use Cycled Video, but Looped Video is a weird thing.

2023-04-11 05:00 UTC, bwsw commented on docs/adapters.md
> +  - [The Looped Video File Source Adapter](#the-looped-video-file-source-adapter)
Even better to change to "Video Loop Source Adapter".

2023-04-12 10:08 UTC, dorgun requested changes
Not implemented "Make It possible to configure a random loss rate, the parameter which makes the adapter randomly drop certain frames (needed to stress the module)."

2023-04-12 11:49 UTC, tomskikh commented on adapters/gst/gst_plugins/python/media_files_src_bin.py
> +        if self.source.get_factory().get_name() != 'filesrc':
This needed to change "souphttpsrc" to "filesrc".

2023-04-12 11:50 UTC, tomskikh commented on adapters/gst/gst_plugins/python/media_files_src_bin.py
> +        if self.loop_file and len(self.pending_locations) == 1:
Yes. When the source is HTTP URL then `self.pending_locations` contains that URL and downloaded file location.

2023-04-13 05:41 UTC, tomskikh commented
> Not implemented "Make It possible to configure a random loss rate, the parameter which makes the adapter randomly drop certain frames (needed to stress the module)."

@dorgun Now it's implemented.

2023-04-13 09:49 UTC, dorgun approved these changes

2023-04-13 10:40 UTC, bwsw approved these changes

2023-04-13 10:50 UTC, merged