#202 implement ffmpeg source element
insight-platform/Savant pull request #259
Opened 2023-06-22 05:59 UTC by tomskikh

2023-06-22 08:09 UTC, bwsw requested changes

2023-06-22 08:09 UTC, bwsw commented on adapters/gst/gst_plugins/python/ffmpeg_src.py
> +        codec = CONVERT_CODEC[frame_params.codec_name]
Please add a check and termination with a correct message that codec is not supported if not in list. The current termination is not user-friendly.

2023-06-22 08:15 UTC, bwsw commented on docs/adapters.md
> +- `FFMPEG_PARAMS` - parameters for FFmpeg source; comma separated string `key=value` (e.g. `rtsp_transport=tcp`, `input_format=mjpeg,video_size=1280x720`);
Please, add `FFMPEG_LOGLEVEL` to params.

2023-07-05 04:37 UTC, dorgun approved these changes

2023-07-05 05:51 UTC, closed without merging