#244 conditional video processing
insight-platform/Savant pull request #262
Opened 2023-06-27 10:38 UTC by tomskikh

2023-06-27 11:07 UTC, bwsw requested changes

2023-06-27 11:07 UTC, bwsw commented on samples/conditional_video_processing/demo.yml
> +        person_face:
must be for 'person', not 'person_face'

2023-06-27 11:07 UTC, bwsw commented on samples/conditional_video_processing/demo.yml
> +        person_noface:
remove this.

2023-06-27 11:07 UTC, bwsw commented on samples/conditional_video_processing/demo.yml
> +    - element: nvtracker
remove it.

2023-06-27 11:07 UTC, bwsw commented on samples/conditional_video_processing/demo.yml
> +    - element: pyfunc
remove it

2023-06-27 11:07 UTC, bwsw commented on samples/conditional_video_processing/demo.yml
> +    module: samples.peoplenet_detector.overlay
remove custom drawfunc, default draw func must be used configured to draw only 'peoplenet.person' objects.

2023-07-05 06:55 UTC, abramov-oleg requested changes
Let's also add a README that briefly describes what the sample shows; mention that it is expected that the AOsink is regularly switching between video stream and stub img.

Add a link to the sample to the `samples/README.md`.

2023-07-06 04:57 UTC, bwsw approved these changes

2023-07-06 04:58 UTC, merged