yolov8 seg demo
insight-platform/Savant pull request #312
Opened 2023-07-20 13:10 UTC by denisvmedyantsev

2023-08-04 08:08 UTC, abramov-oleg requested changes

2023-08-04 08:08 UTC, abramov-oleg commented on samples/yolov8_seg/README.md
> +We created an ONNX version of the YOLOv8m-seg model using a script from the original repository (see [Export section](https://docs.ultralytics.com/tasks/segment/#export)). To process the model output
```[convertor](module/converter.py)```

Convertor / converter spelling inconsistency.

I suggest `converter`

2023-08-04 08:08 UTC, abramov-oleg commented on samples/yolov8_seg/module/converter.py
> +            (int(ratio_x * model.input.width), int(ratio_y * model.input.height)),
If resize ratios were calculated then it is possible to use them directly in the `cv2.resize()` call

Something along the lines of

```
cv2.resize(
        masks,
        dsize=None,
        fx=ratio_x,
        fy=ratio_y,
        cv2.INTER_LINEAR,
```

2023-08-04 08:08 UTC, abramov-oleg commented on samples/yolov8_seg/README.md
> +# YOLOv8 Instance Segmentation
Our samples usually have a .webp preview.

Can we add one for this demo too?

2023-08-04 08:08 UTC, abramov-oleg commented on samples/yolov8_seg/README.md
> +# YOLOv8 Instance Segmentation
Let's add a link to this demo from `samples/README.md`

2023-08-04 08:08 UTC, abramov-oleg commented on samples/yolov8_seg/module/module.yml
> +          # COCO classes {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12
Is the full coco classes list in a single line necessary here?

Seems too verbose.

2023-08-11 22:21 UTC, denisvmedyantsev commented on samples/yolov8_seg/README.md
> +# YOLOv8 Instance Segmentation
Added

2023-08-11 22:21 UTC, denisvmedyantsev commented on samples/yolov8_seg/README.md
> +# YOLOv8 Instance Segmentation
Done

2023-08-11 22:23 UTC, denisvmedyantsev commented on samples/yolov8_seg/README.md
> +We created an ONNX version of the YOLOv8m-seg model using a script from the original repository (see [Export section](https://docs.ultralytics.com/tasks/segment/#export)). To process the model output
Replaced with `converter`.

2023-08-11 22:27 UTC, denisvmedyantsev commented on samples/yolov8_seg/module/converter.py
> +            (int(ratio_x * model.input.width), int(ratio_y * model.input.height)),
Model input 640x640, mask output 160x160, I can't use `ratio_x` directly.

2023-08-11 22:27 UTC, denisvmedyantsev commented on samples/yolov8_seg/module/module.yml
> +          # COCO classes {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12
Removed.

2023-08-15 10:52 UTC, abramov-oleg approved these changes

2023-08-15 12:13 UTC, merged