Add video padding and scaling information to the protocol
insight-platform/Savant pull request #333
Opened 2023-08-01 08:51 UTC by tomskikh

2023-08-14 06:09 UTC, abramov-oleg requested changes

2023-08-14 06:09 UTC, abramov-oleg commented on savant/gstreamer/metadata.py
> +    else:
Unnecessary `elif` and `else`

2023-08-14 06:09 UTC, abramov-oleg commented on savant/api/builder.py
> +    else:
Unnecessary `elif` and `else`

2023-08-14 06:09 UTC, abramov-oleg commented on savant/gstreamer/metadata.py
> +]
Are these types useful?

As I see it, the transformation tuples are built from dicts and are consumed as dicts. Can they just be dicts?

2023-08-23 07:45 UTC, tomskikh commented on savant/gstreamer/metadata.py
> +    else:
Reworked this PR after merging https://github.com/insight-platform/Savant/pull/367

2023-08-23 08:38 UTC, abramov-oleg approved these changes

2023-08-23 10:26 UTC, merged