Move to DS 6.3
insight-platform/Savant pull request #383
Opened 2023-08-28 22:58 UTC by denisvmedyantsev

#347

2023-09-04 08:06 UTC, tomskikh requested changes

2023-09-04 08:06 UTC, tomskikh commented on Makefile
> +	DOCKER_BUILDKIT=1 docker buildx build \
Do we need `DOCKER_BUILDKIT=1` here? AFAIK `buildx` already uses buildkit.

2023-09-04 08:06 UTC, tomskikh commented on docker/Dockerfile.deepstream
> +ARG CMAKE_VER=3.24.2
Why cmake here was downgraded from `3.26.3` to `3.24.2`?

2023-09-04 08:06 UTC, tomskikh commented on docker/Dockerfile.deepstream
> +ARG TARGETARCH
The line is duplicated

2023-09-04 08:06 UTC, tomskikh commented on docker/Dockerfile.deepstream
> +COPY requirements requirements
Each file from requirements was copied with a separate instruction for faster builds. E.g. when savant-rs is updated `docker build` won't install dependencies from other files again.

2023-09-04 08:06 UTC, tomskikh commented on docker/Dockerfile.deepstream
> +# remove samples to reduce image size (~1Gb)
Does it affect the image size? Samples are still present in some layer anyway.

2023-09-04 08:06 UTC, tomskikh commented on savant/deepstream/pipeline.py
> +        #  https://forums.developer.nvidia.com/t/nvjpegdec-produces-transparent-frames/223005
Is this issue still present on DS 6.3? They said it was fixed https://forums.developer.nvidia.com/t/nvjpegdec-produces-transparent-frames/223005/16

2023-09-04 09:08 UTC, denisvmedyantsev commented on Makefile
> +	DOCKER_BUILDKIT=1 docker buildx build \
You are right. Removed.

2023-09-04 09:13 UTC, denisvmedyantsev commented on docker/Dockerfile.deepstream
> +ARG CMAKE_VER=3.24.2
It doesn't matter here. I made this dockerfile from two, x86 and l4t, and used the cmake version from l4t.

2023-09-04 09:19 UTC, denisvmedyantsev commented on docker/Dockerfile.deepstream
> +ARG TARGETARCH
Removed

2023-09-04 09:25 UTC, denisvmedyantsev commented on docker/Dockerfile.deepstream
> +# remove samples to reduce image size (~1Gb)
No, it doesn't. Removed lines.

2023-09-04 09:35 UTC, denisvmedyantsev commented on savant/deepstream/pipeline.py
> +        #  https://forums.developer.nvidia.com/t/nvjpegdec-produces-transparent-frames/223005
There is only one problem out of 3 still relevant for 6.3. Fixed comment.

2023-09-04 10:35 UTC, denisvmedyantsev commented on docker/Dockerfile.deepstream
> +COPY requirements requirements
Ok. Split it up.

2023-09-05 06:58 UTC, tomskikh approved these changes

2023-09-05 10:00 UTC, abramov-oleg approved these changes

2023-09-05 11:13 UTC, merged