Unify python and rust logging config
insight-platform/Savant pull request #436
Opened 2023-09-21 10:12 UTC by abramov-oleg

2023-09-21 12:17 UTC, tomskikh requested changes

2023-09-21 12:17 UTC, tomskikh commented on savant/utils/logging/log_utils.py
> +    :return:  A dictionary of of the form log_target:log_level.
```suggestion
    :return:  A dictionary of the form log_target:log_level.
```

2023-09-21 12:17 UTC, tomskikh commented on savant/utils/logging/log_utils.py
> +    log_spec_str = log_spec_str.lower()
Can target only be in lowercase?

2023-09-21 12:17 UTC, tomskikh commented on savant/utils/logging/log_utils.py
> +    :return:  A dictionary of of the form log_target:log_level.
Fix this in other places too

2023-09-22 03:06 UTC, abramov-oleg commented on savant/utils/logging/log_utils.py
> +    :return:  A dictionary of of the form log_target:log_level.
Fixed.

2023-09-22 03:18 UTC, abramov-oleg commented on savant/utils/logging/log_utils.py
> +    log_spec_str = log_spec_str.lower()
You're right, it's possible that log targets will differ only in case, even though it's unconventional.

Fixed.

2023-09-22 03:22 UTC, tomskikh commented on savant/utils/logging/log_utils.py
> +                if log_directive in LOG_LEVEL_STR_TO_RS:
```suggestion
                log_directive = log_directive
                # no = sign, i.e. only target or only level
                if log_directive.lower() in LOG_LEVEL_STR_TO_RS:
```

2023-09-22 03:27 UTC, abramov-oleg commented on savant/utils/logging/log_utils.py
> +                if log_directive in LOG_LEVEL_STR_TO_RS:
Removed unnecessary assignment line.

2023-09-22 05:24 UTC, tomskikh approved these changes

2023-09-22 05:28 UTC, merged