Intersection traffic meter sample
insight-platform/Savant pull request #477
Opened 2023-10-05 12:20 UTC by abramov-oleg

2023-10-10 04:09 UTC, dorgun requested changes

2023-10-10 04:09 UTC, dorgun commented on samples/intersection_traffic_meter/utils.py
> +def hsv_to_rgb(h, s, v) -> Tuple[int, int, int]:
There is no need to write your own converter, you can use `hsv_to_rgb` from the standard library `colorsys`

2023-10-10 04:24 UTC, abramov-oleg commented on samples/intersection_traffic_meter/utils.py
> +def hsv_to_rgb(h, s, v) -> Tuple[int, int, int]:
Replaced custom converter with the `colorsys` one in both traffic meter and intersection traffic meter.

2023-10-11 03:02 UTC, dorgun approved these changes

2023-10-11 03:04 UTC, merged