Fix module processing of restarted multi-stream adapter
insight-platform/Savant pull request #506
Opened 2023-10-18 04:03 UTC by tomskikh

2023-10-18 08:22 UTC, denisvmedyantsev requested changes

2023-10-18 08:22 UTC, denisvmedyantsev commented on savant/utils/zeromq.py
>              if routing_id in self.routing_ids_cache:
This will be false every time.

2023-10-18 10:57 UTC, tomskikh commented on savant/utils/zeromq.py
>              if routing_id in self.routing_ids_cache:
Fixed

2023-10-18 12:22 UTC, denisvmedyantsev approved these changes

2023-10-18 12:27 UTC, merged

2023-10-19 10:01 UTC, bwsw commented
Closes #495