357 keypoint detection demo
insight-platform/Savant pull request #533
Opened 2023-10-27 11:41 UTC by dorgun

2023-10-31 07:19 UTC, abramov-oleg requested changes

2023-10-31 07:19 UTC, abramov-oleg commented on samples/keypoint_detection/overlay.py
> +import numpy as np
Need to run `make reformat`

2023-10-31 07:19 UTC, abramov-oleg commented on samples/README.md
> +![](keypoint_detection/assets/shuffle_dance-400.webp)
No assets in the PR.

2023-10-31 07:19 UTC, abramov-oleg commented on samples/keypoint_detection/module.yml
> +name: ${oc.env:MODULE_NAME, 'keypoint_detection'}
```suggestion
name: keypoint_detection
```

For consistency with incoming changes for Denis' PR.

2023-10-31 07:19 UTC, abramov-oleg commented on savant/utils/artist/artist_gpumat.py
> +    ):
Let's add a line type parameter with `cv2.LINE_AA` default value.

2023-11-01 04:35 UTC, dorgun commented on samples/keypoint_detection/overlay.py
> +import numpy as np
formatted

2023-11-01 04:37 UTC, dorgun commented on samples/README.md
> +![](keypoint_detection/assets/shuffle_dance-400.webp)
Added

2023-11-01 04:37 UTC, dorgun commented on savant/utils/artist/artist_gpumat.py
> +    ):
Added

2023-11-01 05:00 UTC, abramov-oleg approved these changes

2023-11-01 05:03 UTC, merged