RT-DETR r50 demo
insight-platform/Savant pull request #562
Opened 2023-11-20 11:01 UTC by abramov-oleg

2023-11-27 11:15 UTC, denisvmedyantsev requested changes

2023-11-27 11:15 UTC, denisvmedyantsev commented on samples/rtdetr/README.md
> +Run the demo:
Please refactor according to other samples: add prerequisite and the build engine stage

2023-11-27 11:15 UTC, denisvmedyantsev commented on samples/rtdetr/docker-compose.x86.yml
> +      - FPS_PERIOD=1000
Refactor to use the new FPS meter. Or just remove FPS_PERIOD, I don't think it's important to change the FPS measurement period here.

2023-11-28 12:32 UTC, abramov-oleg commented on samples/rtdetr/README.md
> +Run the demo:
Refactored README.

2023-11-28 12:32 UTC, abramov-oleg commented on samples/rtdetr/docker-compose.x86.yml
> +      - FPS_PERIOD=1000
Removed FPS_PERIOD.

2023-11-28 13:40 UTC, denisvmedyantsev approved these changes

2023-11-28 13:49 UTC, merged