549 savant pytorch integration
insight-platform/Savant pull request #595
Opened 2023-12-11 08:49 UTC by dorgun

2023-12-13 09:36 UTC, abramov-oleg requested changes

2023-12-13 09:36 UTC, abramov-oleg commented on docs/source/advanced_topics/12_torch_hub.rst
> +The `official documentation <https://pytorch.org/docs/stable/hub.html#loading-models-from-hub>`__  describes how to load the model and perform the inference you can.
```suggestion
The `official documentation <https://pytorch.org/docs/stable/hub.html#loading-models-from-hub>`__  describes how to load the model and perform the inference.
```

2023-12-13 09:36 UTC, abramov-oleg commented on docs/source/advanced_topics/12_torch_hub.rst
> +Using Savant you can easily make an inference on a frame or for an object of interest (`example <https://github.com/insight-platform/Savant/tree/develop/samples/panoptic_driving_perception>`__. Also
```suggestion
With Savant it is easy to run Pytorch inference on a frame or for an object of interest. Look at the `panoptic_driving_perception <https://github.com/insight-platform/Savant/tree/develop/samples/panoptic_driving_perception>`__ sample to learn how. Note how OpenCV GPUMat <-> Pytorch GPU tensor conversion function (:ref:`advanced_topics/11_memory_representation_function:Conversions Between GPU Memory Formats`) makes it possible to get the image as a Pytorch GPU tensor and perform the necessary preprocessing exactly as in a strictly Pytorch pipeline, while avoiding copying data to the host memory and back to the GPU.
```

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/pytorch_infer.py
> +from savant.utils.artist import Artist
Import is not used.

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        print(sys.path)
Debug print? Better to remove, I think.

2023-12-13 09:36 UTC, abramov-oleg commented on docs/source/advanced_topics/12_torch_hub.rst
> +    Be careful when installing dependencies necessary for the model to work, because explicitly or implicitly a version of OpenCV without CUDA support may be installed in the Savant docker container.
```suggestion
.. note::

    Be careful when installing dependencies and additional packages. Savant docker container comes with OpenCV with CUDA support preinstalled, and using other OpenCV versions may cause errors and make it impossible to run the code.
```

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/README.md
> +
One line too many at the end of the file, let's remove.

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        self.model.eval()
Currently, the model is loaded in fp32 mode.

Seems like we usually use fp16 and it wouldn't be too difficult to do fp16 inference here as well.

Up to you.

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/pytorch_infer.py
> +            with torch.no_grad():
The modern replacement for the `no_grad` mode in Pytorch is [inference_mode](https://github.com/ailzhang/rfcs/blob/rfc0011/RFC-0011-InferenceMode.md) / [doc](https://pytorch.org/docs/stable/generated/torch.inference_mode.html)

Suggest using `inference_mode`

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/pytorch_infer.py
> +                ll_seg_out = ll_seg_out.detach()
Should be a no-op under `no_grad`, suggest removing.

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        self.logger.debug('Got GST_NVEVENT_STREAM_EOS for source %s.', source_id)
Doesn't seem useful, suggest removing.

2023-12-13 09:36 UTC, abramov-oleg commented on samples/panoptic_driving_perception/docker/Dockerfile.l4t
> +
Extra line.

2023-12-13 10:23 UTC, bwsw commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        self.model.eval()
Why use fp32?

2023-12-21 05:58 UTC, dorgun commented on samples/panoptic_driving_perception/docker/Dockerfile.l4t
> +
Removed

2023-12-21 05:58 UTC, dorgun commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        self.logger.debug('Got GST_NVEVENT_STREAM_EOS for source %s.', source_id)
Removed

2023-12-21 05:58 UTC, dorgun commented on samples/panoptic_driving_perception/pytorch_infer.py
> +                ll_seg_out = ll_seg_out.detach()
Fixed

2023-12-21 05:59 UTC, dorgun commented on samples/panoptic_driving_perception/pytorch_infer.py
> +            with torch.no_grad():
Done

2023-12-21 05:59 UTC, dorgun commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        self.model.eval()
Switched to half-precision

2023-12-21 05:59 UTC, dorgun commented on samples/panoptic_driving_perception/pytorch_infer.py
> +        print(sys.path)
Removed

2023-12-21 05:59 UTC, dorgun commented on samples/panoptic_driving_perception/pytorch_infer.py
> +from savant.utils.artist import Artist
Removed

2023-12-21 08:21 UTC, bwsw approved these changes

2023-12-21 08:22 UTC, merged