Filename pattern fixes
insight-platform/Savant pull request #867
Opened 2024-09-24 12:50 UTC by bwsw

2024-09-26 08:49 UTC, tomskikh requested changes

2024-09-26 08:49 UTC, tomskikh commented on adapters/python/sinks/metadata_json.py
> +        self.logger.info(f'File name pattern is {self.pattern}')
```suggestion
        self.logger.info('File name pattern is %s', self.pattern)
```

2024-09-26 08:49 UTC, tomskikh commented on adapters/python/sinks/metadata_json.py
> +            json.dump(metadata, self.file, indent=4)
Make it optional to write pretty JSONs vs one JSON per line.

2024-09-26 08:49 UTC, tomskikh commented on docs/source/savant_101/10_adapters.rst
> +- ``DIR_LOCATION``: a location to write files to; can be a regular path or a path template; supported substitution parameters are ``%source_id``, ``%src_filename``, and ``%chunk_idx``;
Adding `%src_filename` does not work. It tooks a filename from the first frame. These are files, created by `image-json-sink` in `source_adapter_with_json_metadata` sample:
```
results/
├── coco-images-00000000-000000000785
│   ├── images
│   │   ├── 00000000.jpeg
│   │   ├── 00000001.jpeg
│   │   ├── 00000002.jpeg
│   │   ├── 00000003.jpeg
│   │   └── 00000004.jpeg
│   └── metadata.json
└── coco-images-00000001-000000000785
    ├── images
    │   ├── 00000000.jpeg
    │   ├── 00000001.jpeg
    │   ├── 00000002.jpeg
    │   ├── 00000003.jpeg
    │   └── 00000004.jpeg
    └── metadata.json
```

Sink parameters:
```
      - CHUNK_SIZE=5
      - DIR_LOCATION=/results/%source_id-%chunk_idx-%src_filename
```

2024-09-26 08:49 UTC, tomskikh commented on adapters/python/sinks/image_files.py
> +            base_location = get_location(
Use `base_location` as a key for writer, like in metadata_json.py. That should fix the problem with `%src_filename`.
Same for video_files.py.

2024-09-26 09:03 UTC, bwsw commented on adapters/python/sinks/metadata_json.py
> +            json.dump(metadata, self.file, indent=4)
I removed the identation as I do not want to introduce new parameters.

2024-09-27 04:29 UTC, tomskikh approved these changes

2024-09-27 08:39 UTC, merged